local addonName, ns = ...

ns.Constants = ns.Constants or {}

-- Shared by the outfit slot and the custom-emote editor portrait.
ns.Constants.EMOTE_CATEGORY_ICON =
    "Interface\\Icons\\ability_rogue_disguise"

-- Blizzard's emote globals build the catalog at runtime. These optional
-- overrides give selected entries richer artwork.
ns.Constants.DEFAULT_EMOTE_ICONS = {
    absent = "spell_shadow_nethercloak",
    agree = "thumbup",
    alliance = "inv_banner_tolbarad_alliance",
    amaze = "ability_earthen_wideeyedwonder",
    angry = "spell_misc_emotionangry",
    apologize = "spell_misc_emotionsad",
    applaud = "ability_thunderclap",
    arm = "achievement_reputation_04",
    attackmytarget = "ability_hunter_markedfordeath",
    awe = "achievement_doublerainbow",
    backpack = "inv_backpack_wrathion_c_01",
    badfeeling = "spell_shadow_shadowworddominate",
    bark = "ability_hunter_pet_wolf",
    bashful = "ui_embercourt-emoji-uncomfortable",
    beckon = "ability_hunter_misdirection",
    beg = "spell_holy_prayerofspirit",
    bite = "ability_druid_ferociousbite",
    blame = "spell_holy_fistofjustice",
    blank = "inv_misc_noteblank1a",
    bleed = "ability_warrior_bloodfrenzy",
    blink = "spell_arcane_blink",
    blush = "ui_embercourt-emoji-veryhappy",
    boggle = "sha_ability_rogue_sturdyrecuperate",
    bonk = "inv_hammer_01",
    boop = "inv_mawhand_blue",
    boot = "inv_boots_01",
    bored = "ui_embercourt-emoji-miserable",
    bounce = "ability_racial_rocketjump",
    bow = "achievement_worldevent_dastardlyduos",
    brandish = "inv_sword_1h_cataclysm_b_01",
    brb = "spell_mage_altertime",
    breath = "spell_fire_blueflamebreath",
    burp = "spell_brew_dark",
    bye = "ability_vanish",
    cackle = "inv_12_nonmasculinecharacter_human",
    calm = "ability_worgen_calmthewolf",
    challenge = "achievement_bg_kill_flag_carrierwsg",
    charge = "ability_warrior_charge",
    charm = "spell_shadow_charm",
    cheer = "ability_warrior_rallyingcry",
    chicken = "spell_magic_polymorphchicken",
    chuckle = "achievement_character_bloodelf_female",
    chug = "achievement_guildperk_chug a lug",
    clap = "spell_nature_thunderclap",
    cold = "spell_frost_coldhearted",
    comfort = "ability_hunter_beastsoothe",
    commend = "inv_misc_baradinscommendation",
    confused = "spell_frost_stun",
    congratulate = "inv_misc_trophy_argent",
    cough = "spell_shadow_plaguecloud",
    coverears = "inv_misc_ear_human_02",
    cower = "ability_druid_cower",
    crack = "monk_ability_fistoffury",
    cringe = "spell_misc_emotionafraid",
    crossarms = "ability_warrior_defensivestance",
    cry = "ability_seal",
    cuddle = "spell_druid_bearhug",
    curious = "inv_misc_questionmark",
    curtsey = "inv_dressedhorse",
    dance = "inv_misc_discoball_01",
    ding = "inv_pet_achievement_raiseapetlevel_15",
    disagree = "spell_holy_eyeforaneye",
    doubt = "spell_shadow_mindsteal",
    drink = "inv_drink_07",
    drool = "inv_misc_bowl_01",
    duck = "inv_duck_white",
    eat = "inv_misc_fork&knife",
    embarrass = "achievement_character_undead_female",
    encourage = "ability_paladin_blessedhands",
    enemy = "ability_hunter_snipershot",
    eye = "inv_misc_eye_01",
    eyebrow = "inv_misc_eye_04",
    facepalm = "pandarenracial_quiveringpain",
    fail = "inv_engineering_failure detection pylon",
    faint = "inv_fishing_f_sleeper2",
    fart = "inv_ability_poison_wave",
    fidget = "ui_embercourt-emoji-elated",
    flee = "ability_rogue_fleetfooted",
    flex = "spell_nature_strength",
    flirt = "spell_shadow_summonsuccubus",
    flop = "inv_fishing_lanesnapper",
    follow = "ability_hunter_pathfinding2",
    forthealliance = "achievement_general_allianceslayer",
    forthehorde = "achievement_general_hordeslayer",
    frown = "achievement_character_draenei_female",
    gasp = "ability_rogue_surpriseattack",
    gaze = "ability_bossmannoroth_mannorothsgaze",
    giggle = "achievement_character_orc_female",
    glare = "ability_paladin_blindinglight2",
    gloat = "achievement_character_draenei_male",
    glower = "inv_darkmoon_eye",
    go = "ability_hunter_pathfinding",
    going = "ability_rogue_sprint",
    golfclap = "inv_mawhand_green",
    goodluck = "inv_misc_luckymoneyenvelope",
    greet = "ui_followerdungeon_youlead",
    grin = "achievement_character_dwarf_female",
    groan = "achievement_character_dwarf_male",
    grovel = "spell_holy_prayerofhealing",
    growl = "ability_druid_challangingroar",
    guffaw = "inv_helm_laughingskull_01",
    hail = "inv_misc_horn_01",
    happy = "spell_misc_emotionhappy",
    headache = "ability_mage_brainfreeze",
    healme = "spell_nature_healingtouch",
    hello = "achievement_character_human_male",
    helpme = "ability_evoker_rescue",
    hiccup = "inv_drink_18",
    highfive = "inv_mawhand_purple",
    hiss = "inv_pet_babycrocodile_snarly",
    holdhand = "inv_weapon_hand_08",
    horde = "inv_banner_tolbarad_horde",
    hug = "spell_holy_layonhands",
    hungry = "inv_misc_food_legion_heartyfeast",
    hurry = "spell_druid_feralchargecat",
    huzzah = "inv_pet_achievement_earn100achieve",
    idea = "inv_12_profession_engineering_manufacturedparts_lightbulb_yellow",
    impressed = "spell_holy_greaterblessingofkings",
    incoming = "ability_hunter_crossfire",
    insult = "achievement_character_orc_male",
    introduce = "petjournalportrait",
    jealous = "ability_rogue_bloodyeye",
    jk = "inv_tabard_a_80laughingskull",
    joke = "achievement_character_tauren_male",
    kiss = "spell_shadow_soothingkiss",
    kneel = "ability_paladin_conviction",
    laugh = "achievement_halloween_smiley_01",
    laydown = "ability_druid_dreamstate",
    lean = "ability_rogue_shadowstrikes",
    lick = "ability_creature_disease_02",
    listen = "inv_misc_ear_human_01",
    look = "inv_misc_grouplooking",
    lost = "achievement_dungeon_lostcity of tolvir",
    love = "inv_ragnaros_heart",
    luck = "achievement_guildperk_ladyluck",
    magnificent = "ability_mount_magnificentflyingcarpet",
    map = "inv_misc_map_01",
    massage = "spell_holy_lesserheal",
    meow = "ability_hunter_pet_cat",
    mercy = "spell_holy_healingaura",
    moan = "achievement_character_troll_female",
    mock = "mocking_banner",
    moo = "inv_yakpet",
    moon = "artifactability_balancedruid_fullmoon",
    mountspecial = "inv_brontsaurusmountspecial",
    mourn = "inv_trinket_fragmentoffrostmourne",
    mutter = "spell_shadow_mindshear",
    nervous = "spell_shadow_possession",
    no = "thumbsdown",
    nod = "spell_holy_greaterblessingoflight",
    nosepick = "inv_misc_pignosemask_a_01",
    object = "ability_warrior_disarm",
    offer = "inv_relics_idolofferocity",
    oom = "spell_shadow_manaburn",
    oops = "inv_eng_unstabletemporaltimeshifter",
    openfire = "inv_legendary_gun",
    panic = "spell_nzinsanity_panicattack",
    pat = "inv_mawguardhand_white",
    peer = "ability_hunter_eagleeye",
    pet = "ability_hunter_mendpet",
    pinch = "inv_mawhand_orange",
    pity = "spell_holy_serendipity",
    plead = "spell_holy_prayerofhealing02",
    point = "ability_hunter_pointofnoescape",
    poke = "spell_shadow_fingerofdeath",
    ponder = "spell_nature_crystalball",
    pounce = "ability_druid_ravage",
    pout = "inv_dragonwhelpoutland2_purple",
    praise = "spell_holy_lightsgrace",
    pray = "spell_holy_prayerofmendingtga",
    promise = "70_inscription_deck_promises",
    proud = "inv__faction_proudmooreadmiralty",
    pulse = "ability_deathknight_heartstopaura",
    punch = "inv_legendary_fistweapon",
    purr = "inv_catmount",
    puzzle = "trade_archaeology_cthunspuzzlebox",
    quack = "inv_duck_yellow",
    raise = "spell_shadow_raisedead",
    rasp = "spell_shadow_curseoftongues_amplified",
    read = "inv_misc_book_01",
    ready = "achievement_character_troll_male",
    regret = "achievement_character_pandaren_female",
    revenge = "ability_warrior_revenge",
    roar = "ability_druid_demoralizingroar",
    rofl = "achievement_character_orc_male_brn",
    rolleyes = "sha_ability_rogue_bloodyeye",
    rude = "ability_rogue_dirtydeeds",
    ruffle = "inv_mawguardhand_grey",
    sad = "achievement_character_human_female",
    salute = "spell_holy_stoicism",
    scared = "inv_legendary_chimeraoffear",
    scoff = "achievement_character_tauren_female",
    scold = "ability_rogue_slaughterfromtheshadows",
    scowl = "achievement_character_undead_male",
    scratch = "inv_misc_bearclaw",
    search = "inv_misc_tolbaradsearchlight",
    serious = "achievement_character_nightelf_male",
    sexy = "inv_valentineperfumebottle",
    shake = "ability_shockwave",
    shakefist = "inv_fistofthewhitetiger",
    shifty = "inv_jewelcrafting_nightseye_01",
    shimmy = "rogue_burstofspeed",
    shiver = "ability_mage_chilledtothebone",
    shoo = "inv_mawguardhand_black",
    shout = "ability_warrior_battleshout",
    shrug = "ability_paladin_handoflight",
    shudder = "spell_frost_freezingbreath",
    shy = "achievement_character_gnome_female",
    sigh = "spell_brokenheart",
    signal = "inv_misc_horn_04",
    silence = "spell_holy_silence",
    sing = "spell_holy_divinehymn",
    sit = "inv_fishingchair",
    slap = "ability_monk_palmstrike",
    sleep = "spell_nature_sleep",
    smack = "ability_monk_blackoutkick",
    smile = "achievement_character_gnome_male",
    smirk = "achievement_character_orc_female_brn",
    snap = "ability_rogue_distract",
    snarl = "ability_druid_skinteeth",
    sneak = "ability_hunter_camouflage",
    sneeze = "ability_rogue_smoke",
    snicker = "achievement_character_bloodelf_male",
    sniff = "ability_racial_nosefortrouble",
    snort = "ability_hunter_pet_boar",
    snub = "spell_shadow_auraofdarkness",
    soothe = "ability_priest_bindingprayers",
    spit = "ability_poisons",
    squeal = "inv_babyhornswog_black",
    stand = "ability_warrior_offensivestance",
    stare = "inv_misc_eye_02",
    stink = "spell_shadow_blackplague",
    stopattack = "spell_holy_vindication",
    surprised = "ability_rogue_surpriseattack2",
    surrender = "inv_murlocsurrender",
    suspicious = "ability_rogue_masterofsubtlety",
    sweat = "inv_misc_volatilewater",
    talk = "ability_priest_heavanlyvoice",
    talkex = "warrior_disruptingshout",
    talkq = "inv_archaeology_80_witch_fetishofthequestioningmind",
    tap = "spell_deathknight_runetap",
    taunt = "ability_physical_taunt",
    tease = "inv_11xp_generic_shateaset01",
    thank = "inv_thanksgiving_turkey",
    think = "spell_shadow_brainwash",
    thirsty = "inv_drink_02",
    threaten = "ability_warrior_warcry",
    tickle = "spell_nature_naturetouchgrow",
    tired = "inv_pet_sleepywilly",
    toast = "inv_drink_30_blackheartgrog",
    train = "inv_pet_battlepettraining",
    truce = "achievement_bg_ab_defendflags",
    twiddle = "thumbsup",
    veto = "ability_rogue_kidneyshot",
    victory = "ability_warrior_victoryrush",
    violin = "inv_misc_flute_01",
    wait = "spell_mage_altertime_active",
    warn = "ability_warrior_commandingshout",
    wave = "spell_holy_heal02",
    welcome = "spell_holy_greaterblessingofsalvation",
    whine = "achievement_character_nightelf_female",
    whistle = "inv_misc_whistle_color1",
    whoa = "ui_embercourt-emoji-happy",
    wince = "spell_shadow_painandsuffering",
    wink = "inv_misc_eye_03",
    work = "trade_leatherworking",
    yawn = "spell_nature_drowsy",
    yw = "ability_racial_bestdealsanywhere",
}

-- AnimationData IDs used by the wardrobe's player ModelSceneActor.  These are
-- derived from the retail Emotes and EmotesText DB2 tables; aliases share the
-- same underlying character animation.
ns.Constants.DEFAULT_EMOTE_ANIMATIONS = {}
local function MapEmoteAnimation(animationID, names)
    for name in names:gmatch("%S+") do
        ns.Constants.DEFAULT_EMOTE_ANIMATIONS[name] = animationID
    end
end
MapEmoteAnimation(60, "follow healme joke oom sing talk thank wait yw")
MapEmoteAnimation(61, "drink eat toast")
MapEmoteAnimation(64, "gasp talkex whoa")
MapEmoteAnimation(65, "boggle confused curious lost oops ponder puzzle shrug talkq")
MapEmoteAnimation(66, "bow curtsey")
MapEmoteAnimation(67, "bye greet hail hello wave welcome")
MapEmoteAnimation(68, "alliance cheer congratulate forthealliance forthehorde horde huzzah victory")
MapEmoteAnimation(69, "dance")
MapEmoteAnimation(70, "cackle chuckle giggle gloat guffaw laugh rofl")
MapEmoteAnimation(73, "angry insult rasp rude")
MapEmoteAnimation(74, "attackmytarget growl roar")
MapEmoteAnimation(75, "pray")
MapEmoteAnimation(76, "kiss")
MapEmoteAnimation(77, "cry fail mourn violin")
MapEmoteAnimation(78, "chicken quack taunt")
MapEmoteAnimation(79, "beg grovel mercy plead surrender")
MapEmoteAnimation(80, "applaud clap commend golfclap impressed")
MapEmoteAnimation(81, "flee helpme shout")
MapEmoteAnimation(82, "flex")
MapEmoteAnimation(83, "bashful blush flirt shy")
MapEmoteAnimation(84, "blame boop charge incoming object openfire point")
MapEmoteAnimation(94, "mountspecial")
MapEmoteAnimation(95, "boot")
MapEmoteAnimation(113, "salute")
MapEmoteAnimation(185, "magnificent nod")
MapEmoteAnimation(186, "disagree doubt no")
MapEmoteAnimation(195, "train")
MapEmoteAnimation(225, "cower scared")
MapEmoteAnimation(506, "sniff")
MapEmoteAnimation(520, "read")
MapEmoteAnimation(1260, "lean")

-- Emotes whose Emotes.db2 flags include 0x4000 (Only while still).  Their
-- text or voice line may still play during movement, but the animation will
-- be suppressed unless the player is stationary when the emote fires.
ns.Constants.DEFAULT_EMOTES_REQUIRE_STILL = {}
for name in ("bashful beg blush boot bow curtsey dance flirt grovel kneel "
    .. "laydown lean mercy mountspecial plead pray read shy sit sleep stand "
    .. "surrender"):gmatch("%S+") do
    ns.Constants.DEFAULT_EMOTES_REQUIRE_STILL[name] = true
end

ns.Constants.DEFAULT_EMOTE_INFO = {
    absent = { example = "You look absent-minded.", animation = false, voiceline = false },
    agree = { example = "You agree.", animation = false, voiceline = false },
    alliance = { example = "[No text. Character cheers and says \"For the Alliance!\"]", animation = true, voiceline = true },
    amaze = { example = "You are amazed!", animation = false, voiceline = false },
    angry = { example = "You raise your fist in anger.", animation = true, voiceline = false },
    apologize = { example = "You apologize to everyone. Sorry!", animation = false, voiceline = true },
    applaud = { example = "You applaud. Bravo!", animation = true, voiceline = true },
    arm = { example = "You stretch your arms out.", animation = false, voiceline = false },
    attackmytarget = { example = "You tell everyone to attack something.", animation = true, voiceline = true },
    awe = { example = "You look around in awe.", animation = false, voiceline = false },
    backpack = { example = "You dig through your backpack.", animation = false, voiceline = false },
    badfeeling = { example = "You have a bad feeling about this...", animation = false, voiceline = false },
    bark = { example = "You bark. Woof woof!", animation = false, voiceline = false },
    bashful = { example = "You are bashful.", animation = true, voiceline = false },
    beckon = { example = "You beckon everyone over to you.", animation = false, voiceline = false },
    beg = { example = "You beg everyone around you. How pathetic.", animation = true, voiceline = true },
    bite = { example = "You look around for someone to bite.", animation = false, voiceline = false },
    blame = { example = "You blame yourself for what happened.", animation = true, voiceline = false },
    blank = { example = "You stare blankly at your surroundings.", animation = false, voiceline = false },
    bleed = { example = "Blood oozes from your wounds.", animation = false, voiceline = false },
    blink = { example = "You blink your eyes.", animation = false, voiceline = false },
    blush = { example = "You blush.", animation = true, voiceline = false },
    boggle = { example = "You boggle at the situation.", animation = true, voiceline = false },
    bonk = { example = "You bonk yourself on the noggin. Doh!", animation = false, voiceline = false },
    boop = { example = "You boop your own nose. Boop!", animation = true, voiceline = false },
    boot = { example = "You kick into the air.", animation = true, voiceline = false },
    bored = { example = "You are overcome with boredom.  Oh the drudgery!", animation = false, voiceline = true },
    bounce = { example = "You bounce up and down.", animation = false, voiceline = false },
    bow = { example = "You bow down graciously.", animation = true, voiceline = false },
    brandish = { example = "You brandish your weapon fiercely.", animation = false, voiceline = false },
    brb = { example = "You let everyone know you'll be right back.", animation = false, voiceline = false },
    breath = { example = "You take a deep breath.", animation = false, voiceline = false },
    burp = { example = "You let out a loud belch.", animation = false, voiceline = false },
    bye = { example = "You wave goodbye to everyone. Farewell!", animation = true, voiceline = true },
    cackle = { example = "You cackle maniacally at the situation.", animation = true, voiceline = true },
    calm = { example = "You remain calm.", animation = false, voiceline = false },
    challenge = { example = "You put out a challenge to everyone. Bring it on!", animation = false, voiceline = false },
    charge = { example = "You start to charge.", animation = true, voiceline = true },
    charm = { example = "You put on the charm.", animation = false, voiceline = false },
    cheer = { example = "You cheer!", animation = true, voiceline = true },
    chicken = { example = "With arms flapping, you strut around. Cluck, Cluck, Chicken!", animation = true, voiceline = true },
    chuckle = { example = "You let out a hearty chuckle.", animation = true, voiceline = true },
    chug = { example = "You take a mighty quaff of your beverage.", animation = false, voiceline = false },
    clap = { example = "You clap excitedly.", animation = true, voiceline = false },
    cold = { example = "You let everyone know that you are cold.", animation = false, voiceline = false },
    comfort = { example = "You need to be comforted.", animation = false, voiceline = false },
    commend = { example = "You commend everyone on a job well done.", animation = true, voiceline = false },
    confused = { example = "You are hopelessly confused.", animation = true, voiceline = false },
    congratulate = { example = "You congratulate everyone around you.", animation = true, voiceline = true },
    cough = { example = "You let out a hacking cough.", animation = false, voiceline = false },
    coverears = { example = "You cover your ears.", animation = false, voiceline = false },
    cower = { example = "You cower in fear.", animation = true, voiceline = false },
    crack = { example = "You crack your knuckles.", animation = false, voiceline = false },
    cringe = { example = "You cringe in fear.", animation = false, voiceline = false },
    crossarms = { example = "You cross your arms.", animation = false, voiceline = false },
    cry = { example = "You cry.", animation = true, voiceline = true },
    cuddle = { example = "You need to be cuddled.", animation = false, voiceline = false },
    curious = { example = "You express your curiosity to those around you.", animation = true, voiceline = false },
    curtsey = { example = "You curtsey.", animation = true, voiceline = false },
    dance = { example = "You burst into dance.", animation = true, voiceline = false },
    ding = { example = "You reached a new level. DING!", animation = false, voiceline = false },
    disagree = { example = "You disagree.", animation = true, voiceline = false },
    doubt = { example = "You highly doubt the situation will end in your favor.", animation = true, voiceline = false },
    drink = { example = "You raise a drink in the air before chugging it down. Cheers!", animation = true, voiceline = true },
    drool = { example = "A tendril of drool runs down your lip.", animation = false, voiceline = false },
    duck = { example = "You duck for cover.", animation = false, voiceline = false },
    eat = { example = "You begin to eat.", animation = true, voiceline = true },
    embarrass = { example = "You flush with embarrassment.", animation = false, voiceline = false },
    encourage = { example = "You encourage everyone around you.", animation = false, voiceline = false },
    enemy = { example = "You warn everyone that an enemy is near.", animation = false, voiceline = false },
    eye = { example = "You cross your eyes.", animation = false, voiceline = false },
    eyebrow = { example = "You raise your eyebrow inquisitively.", animation = false, voiceline = false },
    facepalm = { example = "You cover your face with your palm.", animation = false, voiceline = false },
    fail = { example = "You have failed.", animation = true, voiceline = true },
    faint = { example = "You faint.", animation = false, voiceline = false },
    fart = { example = "You fart loudly.  Whew...what stinks?", animation = false, voiceline = false },
    fidget = { example = "You fidget.", animation = false, voiceline = false },
    flee = { example = "You yell for everyone to flee!", animation = true, voiceline = true },
    flex = { example = "You flex your muscles. Oooooh so strong!", animation = true, voiceline = false },
    flirt = { example = "You flirt.", animation = true, voiceline = true },
    flop = { example = "You flop about helplessly.", animation = false, voiceline = false },
    follow = { example = "You motion for everyone to follow.", animation = true, voiceline = true },
    forthealliance = { example = "You cheer for the Alliance!", animation = true, voiceline = true },
    forthehorde = { example = "You cheer for the Horde!", animation = true, voiceline = true },
    frown = { example = "You frown.", animation = false, voiceline = false },
    gasp = { example = "You gasp.", animation = true, voiceline = false },
    gaze = { example = "You gaze off into the distance.", animation = false, voiceline = false },
    giggle = { example = "You giggle.", animation = true, voiceline = true },
    glare = { example = "You glare angrily.", animation = false, voiceline = false },
    gloat = { example = "You gloat over everyone's misfortune.", animation = true, voiceline = true },
    glower = { example = "You glower at averyone around you.", animation = false, voiceline = false },
    go = { example = "You tell everyone to go.", animation = false, voiceline = false },
    going = { example = "You must be going.", animation = false, voiceline = false },
    golfclap = { example = "You clap half-heartedly, clearly unimpressed.", animation = true, voiceline = false },
    goodluck = { example = "You wish for some good luck.", animation = false, voiceline = false },
    greet = { example = "You greet everyone warmly.", animation = true, voiceline = false },
    grin = { example = "You grin wickedly.", animation = false, voiceline = false },
    groan = { example = "{{text|poor|You begin to groan.}}<br/>You begin to groan in pain.", animation = false, voiceline = false },
    grovel = { example = "You grovel on the ground, wallowing in subservience.", animation = true, voiceline = false },
    growl = { example = "You growl menacingly.", animation = true, voiceline = false },
    guffaw = { example = "You let out a boisterous guffaw!", animation = true, voiceline = true },
    hail = { example = "You hail those around you.", animation = true, voiceline = false },
    happy = { example = "You are filled with happiness!", animation = false, voiceline = false },
    headache = { example = "You are getting a headache.", animation = false, voiceline = false },
    healme = { example = "You call out for healing!", animation = true, voiceline = true },
    hello = { example = "You greet everyone with a hearty hello!", animation = true, voiceline = true },
    helpme = { example = "You cry out for help!", animation = true, voiceline = true },
    hiccup = { example = "You hiccup loudly.", animation = false, voiceline = false },
    highfive = { example = "You put up your hand for a high five.", animation = false, voiceline = false },
    hiss = { example = "You hiss at everyone around you.", animation = false, voiceline = false },
    holdhand = { example = "You wish someone would hold your hand.", animation = false, voiceline = false },
    horde = { example = "[No text. Character cheers and says \"For the Horde!\"]", animation = true, voiceline = true },
    hug = { example = "You need a hug!", animation = false, voiceline = false },
    hungry = { example = "You are hungry!", animation = false, voiceline = false },
    hurry = { example = "You try to pick up the pace.", animation = false, voiceline = false },
    huzzah = { example = "You cheer boisterously! Huzzah!", animation = true, voiceline = false },
    idea = { example = "You have an idea!", animation = false, voiceline = false },
    impressed = { example = "You clap vigorously, clearly impressed.", animation = true, voiceline = false },
    incoming = { example = "You warn everyone of incoming enemies!", animation = true, voiceline = true },
    insult = { example = "You think everyone around you is a son of a motherless ogre.", animation = true, voiceline = false },
    introduce = { example = "You introduce yourself to everyone.", animation = false, voiceline = false },
    jealous = { example = "You are jealous of everyone around you.", animation = false, voiceline = false },
    jk = { example = "You were just kidding!", animation = false, voiceline = false },
    joke = { example = "You tell a joke.", animation = true, voiceline = true },
    kiss = { example = "You blow a kiss into the wind.", animation = true, voiceline = true },
    kneel = { example = "You kneel down.", animation = true, voiceline = false },
    laugh = { example = "You laugh.", animation = true, voiceline = true },
    laydown = { example = "You lie down.", animation = true, voiceline = false },
    lean = { example = "You lean back.", animation = true, voiceline = false },
    lick = { example = "You lick your lips.", animation = false, voiceline = false },
    listen = { example = "You are listening!", animation = false, voiceline = false },
    look = { example = "You look around.", animation = false, voiceline = false },
    lost = { example = "You are hopelessly lost.", animation = true, voiceline = false },
    love = { example = "You feel the love.", animation = false, voiceline = false },
    luck = { example = "You wish everyone good luck.", animation = false, voiceline = false },
    magnificent = { example = "You nod approvingly. Magnificent job!", animation = true, voiceline = false },
    map = { example = "You pull out your map.", animation = false, voiceline = false },
    massage = { example = "You need a massage!", animation = false, voiceline = false },
    meow = { example = "You meow.", animation = false, voiceline = false },
    mercy = { example = "You plead for mercy.", animation = true, voiceline = false },
    moan = { example = "You moan suggestively.", animation = false, voiceline = false },
    mock = { example = "You mock life and all it stands for.", animation = false, voiceline = false },
    moo = { example = "Mooooooooooo.", animation = false, voiceline = true },
    moon = { example = "You drop your trousers and moon everyone.", animation = false, voiceline = false },
    mountspecial = { example = "[No text. Causes mount to perform an animation.]", animation = true, voiceline = false },
    mourn = { example = "In quiet contemplation, you mourn the loss of the dead.", animation = true, voiceline = true },
    mutter = { example = "You mutter angrily to yourself. Hmmmph!", animation = false, voiceline = false },
    nervous = { example = "You look around nervously.", animation = false, voiceline = false },
    no = { example = "You clearly state, NO.", animation = true, voiceline = true },
    nod = { example = "You nod.", animation = true, voiceline = true },
    nosepick = { example = "With a finger deep in one nostril, you pass the time.", animation = false, voiceline = false },
    object = { example = "You OBJECT!", animation = true, voiceline = false },
    offer = { example = "You want to make an offer.", animation = false, voiceline = false },
    oom = { example = "You announce that you have low mana!", animation = true, voiceline = true },
    oops = { example = "You made a mistake.", animation = true, voiceline = true },
    openfire = { example = "You give the order to open fire.", animation = true, voiceline = true },
    panic = { example = "You run around in a frenzied state of panic.", animation = false, voiceline = false },
    pat = { example = "You need a pat.", animation = false, voiceline = false },
    peer = { example = "You peer around, searchingly.", animation = false, voiceline = false },
    pet = { example = "You need to be petted.", animation = false, voiceline = false },
    pinch = { example = "You pinch yourself.", animation = false, voiceline = false },
    pity = { example = "You pity those around you.", animation = false, voiceline = false },
    plead = { example = "You drop to your knees and plead in desperation.", animation = true, voiceline = false },
    point = { example = "You point over yonder.", animation = true, voiceline = false },
    poke = { example = "You poke your belly and giggle.", animation = false, voiceline = false },
    ponder = { example = "You ponder the situation.", animation = true, voiceline = false },
    pounce = { example = "You pounce out from the shadows.", animation = false, voiceline = false },
    pout = { example = "You pout at everyone around you.", animation = false, voiceline = false },
    praise = { example = "You praise the Light.", animation = false, voiceline = false },
    pray = { example = "You pray to the Gods.", animation = true, voiceline = false },
    promise = { example = "You make your target a promise.", animation = false, voiceline = false },
    proud = { example = "You are proud of yourself.", animation = false, voiceline = false },
    pulse = { example = "You check your own pulse.", animation = false, voiceline = false },
    punch = { example = "You punch yourself.", animation = false, voiceline = false },
    purr = { example = "You purr like a kitten.", animation = false, voiceline = false },
    puzzle = { example = "You are puzzled. What's going on here?", animation = true, voiceline = false },
    quack = { example = "You pretend to be a duck. Quack!", animation = true, voiceline = false },
    raise = { example = "You raise your hand in the air.", animation = false, voiceline = false },
    rasp = { example = "You make a rude gesture.", animation = true, voiceline = true },
    read = { example = "[No text. Character opens and reads their map.]", animation = true, voiceline = false },
    ready = { example = "You let everyone know that you are ready!", animation = false, voiceline = false },
    regret = { example = "You are filled with regret.", animation = false, voiceline = false },
    revenge = { example = "You vow you will have your revenge.", animation = false, voiceline = false },
    roar = { example = "You roar with bestial vigor. So fierce!", animation = true, voiceline = true },
    rofl = { example = "You roll on the floor laughing.", animation = true, voiceline = true },
    rolleyes = { example = "You roll your eyes.", animation = false, voiceline = false },
    rude = { example = "You make a rude gesture.", animation = true, voiceline = true },
    ruffle = { example = "You ruffle your hair.", animation = false, voiceline = false },
    sad = { example = "You hang your head dejectedly.", animation = false, voiceline = false },
    salute = { example = "You stand at attention and salute.", animation = true, voiceline = false },
    scared = { example = "You are scared!", animation = true, voiceline = false },
    scoff = { example = "You scoff.", animation = false, voiceline = false },
    scold = { example = "You scold yourself.", animation = false, voiceline = false },
    scowl = { example = "You scowl.", animation = false, voiceline = false },
    scratch = { example = "You scratch yourself. Ah, much better!", animation = false, voiceline = false },
    search = { example = "You search for something.", animation = false, voiceline = false },
    serious = { example = "You think this is serious business.", animation = false, voiceline = false },
    sexy = { example = "You're too sexy for your tunic...so sexy it hurts.", animation = false, voiceline = false },
    shake = { example = "You shake your rear.", animation = false, voiceline = false },
    shakefist = { example = "You shake your fist.", animation = false, voiceline = false },
    shifty = { example = "Your eyes shift back and forth suspiciously.", animation = false, voiceline = false },
    shimmy = { example = "You shimmy before the masses.", animation = false, voiceline = false },
    shiver = { example = "You shiver in your boots. Chilling!", animation = false, voiceline = false },
    shoo = { example = "You shoo the measly pests away.", animation = false, voiceline = false },
    shout = { example = "You shout.", animation = true, voiceline = false },
    shrug = { example = "You shrug. Who knows?", animation = true, voiceline = false },
    shudder = { example = "You shudder.", animation = false, voiceline = false },
    shy = { example = "You smile shyly.", animation = true, voiceline = false },
    sigh = { example = "You let out a long, drawn-out sigh.", animation = false, voiceline = true },
    signal = { example = "You give the signal.", animation = false, voiceline = false },
    silence = { example = "You tell everyone to be quiet. Shhh!", animation = false, voiceline = false },
    sing = { example = "You burst into song.", animation = true, voiceline = false },
    sit = { example = "[No text. Character sits down.]", animation = true, voiceline = false },
    slap = { example = "You slap yourself across the face. Ouch!", animation = false, voiceline = false },
    sleep = { example = "You fall asleep.  Zzzzzzz.", animation = true, voiceline = false },
    smack = { example = "You smack your forehead.", animation = false, voiceline = false },
    smile = { example = "You smile.", animation = false, voiceline = false },
    smirk = { example = "A sly smirk spreads across your face.", animation = false, voiceline = false },
    snap = { example = "You snap your fingers.", animation = false, voiceline = false },
    snarl = { example = "You bare your teeth and snarl.", animation = false, voiceline = false },
    sneak = { example = "You try to sneak away.", animation = false, voiceline = false },
    sneeze = { example = "You sneeze. Achoo!", animation = false, voiceline = false },
    snicker = { example = "You quietly snicker to yourself.", animation = false, voiceline = false },
    sniff = { example = "You sniff the air around you.", animation = true, voiceline = true },
    snort = { example = "You snort.", animation = false, voiceline = false },
    snub = { example = "You snub all of the lowly peons around you.", animation = false, voiceline = false },
    soothe = { example = "You need to be soothed.", animation = false, voiceline = false },
    spit = { example = "You spit on the ground.", animation = false, voiceline = false },
    squeal = { example = "You squeal like a pig.", animation = false, voiceline = false },
    stand = { example = "[No text. The character stands up.]", animation = true, voiceline = false },
    stare = { example = "You stare off into the distance.", animation = false, voiceline = false },
    stink = { example = "You smell the air around you. Wow, someone stinks!", animation = false, voiceline = false },
    stopattack = { example = "You tell everyone to stop attacking.", animation = false, voiceline = false },
    surprised = { example = "You are so surprised!", animation = false, voiceline = false },
    surrender = { example = "You surrender to your opponents.", animation = true, voiceline = false },
    suspicious = { example = "You narrow your eyes in suspicion.", animation = false, voiceline = false },
    sweat = { example = "You are sweating.", animation = false, voiceline = false },
    talk = { example = "You talk to yourself since no one else seems interested.", animation = true, voiceline = false },
    talkex = { example = "You talk excitedly with everyone.", animation = true, voiceline = false },
    talkq = { example = "You want to know the meaning of life.", animation = true, voiceline = false },
    tap = { example = "You tap your foot.  Hurry up already!", animation = false, voiceline = false },
    taunt = { example = "You taunt everyone around you. Bring it fools!", animation = true, voiceline = true },
    tease = { example = "You are such a tease.", animation = false, voiceline = false },
    thank = { example = "You thank everyone around you.", animation = true, voiceline = true },
    think = { example = "You are lost in thought.", animation = false, voiceline = false },
    thirsty = { example = "You are so thirsty. Can anyone spare a drink?", animation = false, voiceline = false },
    threaten = { example = "You threaten everyone with the wrath of doom.", animation = false, voiceline = true },
    tickle = { example = "You want to be tickled. Hee hee!", animation = false, voiceline = false },
    tired = { example = "You let everyone know that you are tired.", animation = false, voiceline = false },
    toast = { example = "You raise a drink in the air before chugging it down. Cheers!", animation = true, voiceline = false },
    train = { example = "[No text. Character pumps their arm and makes a \"choo choo!\" sound.]", animation = true, voiceline = true },
    truce = { example = "You offer a truce.", animation = false, voiceline = false },
    twiddle = { example = "You twiddle your thumbs.", animation = false, voiceline = false },
    veto = { example = "You veto the motion on the floor.", animation = false, voiceline = false },
    victory = { example = "You bask in the glory of victory.", animation = true, voiceline = false },
    violin = { example = "You begin to play the world's smallest violin.", animation = true, voiceline = true },
    wait = { example = "You ask everyone to wait.", animation = true, voiceline = true },
    warn = { example = "You warn everyone.", animation = false, voiceline = false },
    wave = { example = "You wave.", animation = true, voiceline = false },
    welcome = { example = "You welcome everyone.", animation = true, voiceline = true },
    whine = { example = "You whine pathetically.", animation = false, voiceline = false },
    whistle = { example = "You let forth a sharp whistle.", animation = false, voiceline = true },
    whoa = { example = "You are blown away.", animation = true, voiceline = true },
    wince = { example = "You wince sympathetically.", animation = false, voiceline = false },
    wink = { example = "You wink slyly.", animation = false, voiceline = false },
    work = { example = "You begin to work.", animation = false, voiceline = false },
    yawn = { example = "You yawn sleepily.", animation = false, voiceline = true },
    yw = { example = "You were happy to help.", animation = true, voiceline = true },
}
