local _, ns = ...
local L = ns.L

-- Base locale. Keeping these assignments explicit makes this file the
-- authoritative inventory of text that translators need to cover.
local strings = {
    "Account", "Account Wide", "Account Wide Aquatic Mounts", "Apply", "Delete",
    "Account Wide Flying Mounts", "Account Wide Ground Mounts", "Active",
    "Add New Emote", "Add New Loadout", "Add Toy By ID", "Added Toys",
    "Animation", "Apply Loadout", "Aquatic", "Associated Outfits:",
    "Available to", "Cancel", "Character", "Character Title", "Check All",
    "Clear", "Conditions:", "Cosmetic Toys", "Create Character Outfit Update Macro",
    "Create Macro", "Create Outfit Update Macro", "Custom", "Default",
    "Delete Emote", "Delete Loadout", "Disable Hunter Pets", "Disable Pets",
    "Disabled", "Emote text", "Emotes", "Enter a toy item ID", "Flying",
    "General", "Global Cooldown", "Ground", "Hearthstone Macro", "Hearthstones",
    "Hide Duplicate Names", "Hunter Pet", "Hunter Pets", "Icon", "Ignore Hunter Pet",
    "Ignore Pet", "Ignore Pets", "Ignore target", "Ignore Title", "In Stable",
    "Loadouts", "Mount Macro", "Name", "None", "Not Collected", "Outfits",
    "Pets", "Preview", "Random Mount", "Random Pet", "Random Hunter Pet",
    "Remove Added Toy", "Remove Favorite", "Reset", "Reset Default Hearthstones",
    "Save", "Save for", "Save Loadout", "Search", "Search by ID", "Select All",
    "Selected", "Set Favorite", "Stabled", "Summon Mount", "Summon Pet",
    "This Character", "Title", "Title (optional)", "Uncheck All", "Unnamed",
    "Unnamed Loadout", "Update Outfit", "Use Hearthstone", "Voiceline", "Zones",
    "Character Loadout", "Account Wide Loadout", "No Pet", "Random", "Toys",
    "Mounts", "Remove Macro Changes On Update", "Show Tooltip in Mount Macro",
    "Use Druid Macro", "Use Shaman Macro", "Use Zone Specific Mounts",
    "Show Tooltip in Hearthstone Macro", "Astral Recall Fallback",
    "Dismiss Pet On Stealth", "Dismiss Pet In Instances While Grouped", "Revive Pet",
    "Cancel Non-Outfit Cosmetic Toys", "Apply Toy On Select",
    "Auto Enable Zone Situations", "Auto Disable Zone Situations",
    "Page %d/%d", "Ignore %s", "Disable %s", "%s Condition", "%s Condition:",
    "Classic", "Burning Crusade", "Wrath of the Lich King", "Cataclysm",
    "Mists of Pandaria", "Warlords of Draenor", "Legion", "Battle for Azeroth",
    "Shadowlands", "Dragonflight", "The War Within", "Midnight",
    "Humanoid", "Dragonkin", "Undead", "Critter", "Magic", "Elemental", "Beast",
    "Mechanical", "Arctic", "Forest", "Jungle", "Desert", "Plains", "Mountain",
    "Swamp", "Cities", "Biomes", "Social", "Outfit Change", "Enter World", "Mount",
    "Khaz Algar", "K'aresh", "Dragon Isles", "Kul Tiras", "Zandalar", "Nazjatar",
    "Broken Isles", "Argus", "Draenor", "Pandaria", "Northrend", "Outland",
    "Eastern Kingdoms", "Kalimdor", "Elemental Planes",
    "Dismount", "Zone Change", "Leave Stealth", "Mounting", "Dismounting",
    "Entering Combat", "Leaving Combat", "Starting to Eat", "Finishing Eating",
    "Starting to Drink", "Finishing Drinking", "Entering a Rest Area",
    "Leaving a Rest Area", "AFK", "Using a Hearthstone", "Equipping This Outfit",
    "Target Friendly Player", "Target Friendly NPC", "Target Hostile NPC",
    "Drag or click to pick up the macro.", "Right-click for favorite options.",
    "You have not collected this toy.", "Right-click to remove this custom toy.",
    "Valid behavior is not guaranteed.", "Summons a random favorite battle pet.",
    "Selecting a specific pet turns this off.",
    "Summons a random mount from this category.",
    "Selecting specific mounts turns this off.",
    "Select a title for this transmog outfit",
    "Save all Fitter settings from the selected outfit.",
    "Add a toy to Fitter's cosmetic toy list using its item ID.",
    "Leave the currently summoned pet unchanged, except when a global dismissal setting applies.",
    "No conditions selected. This emote can occur whenever its trigger fires.",
    "Select all zones.", "Clear all selected zones.",
    "Reset outfits that have only the default Hearthstone selected?\n\nThis applies now to this character and when each other character on the account next logs in.",
    "Create a macro that updates your outfit by applying toys and titles,",
    "Create a character-specific macro that updates your outfit by applying toys and titles,",
    "The account-wide macro already exists and will be used if no character macro exists.",
    "Apply the loadout |cffffd200%s|r to the currently selected outfit?\n\nThis will replace its current Fitter configuration.",
    "Delete the loadout |cffffd200%s|r?\n\nThis cannot be undone.",
    "Reset all Fitter outfit configurations for this character?\n\nSaved loadouts and custom emotes will be preserved. This cannot be undone.",
    "Reset the Fitter configuration for |cffffd200%s|r?\n\nThis cannot be undone.",
    "Cannot create macro: maximum number of account macros reached.",
    "Created macro '%s'.", "Character macro '%s' already exists.",
    "Cannot create macro: maximum number of character macros reached.",
    "Created character macro '%s'.",
}

for _, text in ipairs(strings) do
    L[text] = text
end
