local _, ns = ...
if GetLocale() ~= "esMX" then return end
local L = ns.L

local translations = {
    ["Account"] = "Cuenta", ["Account Wide"] = "Toda la cuenta",
    ["Apply"] = "Aplicar", ["Delete"] = "Eliminar",
    ["Account Wide Aquatic Mounts"] = "Monturas acuáticas de toda la cuenta",
    ["Account Wide Flying Mounts"] = "Monturas voladoras de toda la cuenta",
    ["Account Wide Ground Mounts"] = "Monturas terrestres de toda la cuenta",
    ["Active"] = "Activo", ["Add New Emote"] = "Añadir gesto nuevo",
    ["Add New Loadout"] = "Añadir configuración nueva",
    ["Add Toy By ID"] = "Añadir juguete por ID", ["Added Toys"] = "Juguetes añadidos",
    ["Animation"] = "Animación", ["Apply Loadout"] = "Aplicar configuración",
    ["Aquatic"] = "Acuática", ["Associated Outfits:"] = "Conjuntos asociados:",
    ["Available to"] = "Disponible para", ["Cancel"] = "Cancelar",
    ["Character"] = "Personaje", ["Character Title"] = "Título del personaje",
    ["Check All"] = "Marcar todo", ["Clear"] = "Borrar", ["Conditions:"] = "Condiciones:",
    ["Cosmetic Toys"] = "Juguetes cosméticos",
    ["Create Character Outfit Update Macro"] = "Crear macro de actualización de conjunto del personaje",
    ["Create Macro"] = "Crear macro",
    ["Create Outfit Update Macro"] = "Crear macro de actualización de conjunto",
    ["Custom"] = "Personalizado", ["Default"] = "Predeterminado",
    ["Delete Emote"] = "Eliminar gesto", ["Delete Loadout"] = "Eliminar configuración",
    ["Disable Hunter Pets"] = "Desactivar mascotas de cazador",
    ["Disable Pets"] = "Desactivar mascotas", ["Disabled"] = "Desactivado",
    ["Emote text"] = "Texto del gesto", ["Emotes"] = "Gestos",
    ["Enter a toy item ID"] = "Introduce el ID de objeto de un juguete",
    ["Flying"] = "Voladora", ["General"] = "General",
    ["Global Cooldown"] = "Tiempo de reutilización global", ["Ground"] = "Terrestre",
    ["Hearthstone Macro"] = "Macro de piedra de hogar", ["Hearthstones"] = "Piedras de hogar",
    ["Hide Duplicate Names"] = "Ocultar nombres duplicados", ["Hunter Pet"] = "Mascota de cazador",
    ["Hunter Pets"] = "Mascotas de cazador", ["Icon"] = "Icono",
    ["Ignore Hunter Pet"] = "Ignorar mascota de cazador", ["Ignore Pet"] = "Ignorar mascota",
    ["Ignore Pets"] = "Ignorar mascotas", ["Ignore target"] = "Ignorar objetivo",
    ["Ignore Title"] = "Ignorar título", ["In Stable"] = "En el establo",
    ["Loadouts"] = "Configuraciones", ["Mount Macro"] = "Macro de montura",
    ["Name"] = "Nombre", ["None"] = "Ninguno", ["Not Collected"] = "No obtenidos",
    ["Outfits"] = "Conjuntos", ["Pets"] = "Mascotas", ["Preview"] = "Vista previa",
    ["Random Mount"] = "Montura aleatoria", ["Random Pet"] = "Mascota aleatoria",
    ["Random Hunter Pet"] = "Mascota de cazador aleatoria",
    ["Remove Added Toy"] = "Eliminar juguete añadido", ["Remove Favorite"] = "Quitar favorito",
    ["Reset"] = "Restablecer", ["Reset Default Hearthstones"] = "Restablecer piedras de hogar predeterminadas",
    ["Save"] = "Guardar", ["Save for"] = "Guardar para", ["Save Loadout"] = "Guardar configuración",
    ["Search"] = "Buscar", ["Search by ID"] = "Buscar por ID", ["Select All"] = "Seleccionar todo",
    ["Selected"] = "Seleccionados", ["Set Favorite"] = "Marcar como favorito",
    ["Stabled"] = "En el establo", ["Summon Mount"] = "Invocar montura",
    ["Summon Pet"] = "Invocar mascota", ["This Character"] = "Este personaje",
    ["Title"] = "Título", ["Title (optional)"] = "Título (opcional)",
    ["Uncheck All"] = "Desmarcar todo", ["Unnamed"] = "Sin nombre",
    ["Unnamed Loadout"] = "Configuración sin nombre", ["Update Outfit"] = "Actualizar conjunto",
    ["Character Loadout"] = "Configuración del personaje",
    ["Account Wide Loadout"] = "Configuración de toda la cuenta",
    ["No Pet"] = "Sin mascota", ["Random"] = "Aleatorio", ["Toys"] = "Juguetes",
    ["Use Hearthstone"] = "Usar piedra de hogar", ["Voiceline"] = "Línea de voz",
    ["Zones"] = "Zonas", ["Page %d/%d"] = "Página %d/%d", ["Ignore %s"] = "Ignorar %s",
    ["Mounts"] = "Monturas", ["Remove Macro Changes On Update"] = "Eliminar cambios de macro al actualizar",
    ["Show Tooltip in Mount Macro"] = "Mostrar descripción en la macro de montura",
    ["Use Druid Macro"] = "Usar macro de druida", ["Use Shaman Macro"] = "Usar macro de chamán",
    ["Use Zone Specific Mounts"] = "Usar monturas específicas de zona",
    ["Show Tooltip in Hearthstone Macro"] = "Mostrar descripción en la macro de piedra de hogar",
    ["Astral Recall Fallback"] = "Usar Regreso astral como alternativa",
    ["Dismiss Pet On Stealth"] = "Retirar mascota al entrar en sigilo",
    ["Dismiss Pet In Instances While Grouped"] = "Retirar mascota en instancias al estar en grupo",
    ["Revive Pet"] = "Revivir mascota",
    ["Cancel Non-Outfit Cosmetic Toys"] = "Cancelar juguetes cosméticos ajenos al conjunto",
    ["Apply Toy On Select"] = "Aplicar juguete al seleccionarlo",
    ["Auto Enable Zone Situations"] = "Activar automáticamente situaciones de zona",
    ["Auto Disable Zone Situations"] = "Desactivar automáticamente situaciones de zona",
    ["Disable %s"] = "Desactivar %s", ["%s Condition"] = "Condición de %s",
    ["%s Condition:"] = "Condición de %s:", ["Classic"] = "Clásico",
    ["Burning Crusade"] = "The Burning Crusade", ["Wrath of the Lich King"] = "Wrath of the Lich King",
    ["Cataclysm"] = "Cataclysm", ["Mists of Pandaria"] = "Mists of Pandaria",
    ["Warlords of Draenor"] = "Warlords of Draenor", ["Legion"] = "Legion",
    ["Battle for Azeroth"] = "Battle for Azeroth", ["Shadowlands"] = "Shadowlands",
    ["Dragonflight"] = "Dragonflight", ["The War Within"] = "The War Within",
    ["Midnight"] = "Midnight", ["Humanoid"] = "Humanoide", ["Dragonkin"] = "Dragonante",
    ["Undead"] = "No-muerto", ["Critter"] = "Alimaña", ["Magic"] = "Magia",
    ["Elemental"] = "Elemental", ["Beast"] = "Bestia", ["Mechanical"] = "Mecánica",
    ["Arctic"] = "Ártico", ["Forest"] = "Bosque", ["Jungle"] = "Jungla",
    ["Desert"] = "Desierto", ["Plains"] = "Llanuras", ["Mountain"] = "Montaña",
    ["Swamp"] = "Pantano", ["Cities"] = "Ciudades", ["Biomes"] = "Biomas",
    ["Khaz Algar"] = "Khaz Algar", ["K'aresh"] = "K'aresh", ["Dragon Isles"] = "Islas Dragón",
    ["Kul Tiras"] = "Kul Tiras", ["Zandalar"] = "Zandalar", ["Nazjatar"] = "Nazjatar",
    ["Broken Isles"] = "Islas Abruptas", ["Argus"] = "Argus", ["Draenor"] = "Draenor",
    ["Pandaria"] = "Pandaria", ["Northrend"] = "Rasganorte", ["Outland"] = "Terrallende",
    ["Eastern Kingdoms"] = "Reinos del Este", ["Kalimdor"] = "Kalimdor",
    ["Elemental Planes"] = "Planos Elementales",
    ["Social"] = "Social", ["Outfit Change"] = "Cambio de conjunto",
    ["Enter World"] = "Entrar al mundo", ["Mount"] = "Montar", ["Dismount"] = "Desmontar",
    ["Zone Change"] = "Cambio de zona", ["Leave Stealth"] = "Salir del sigilo",
    ["Mounting"] = "Al montar", ["Dismounting"] = "Al desmontar",
    ["Entering Combat"] = "Al entrar en combate", ["Leaving Combat"] = "Al salir de combate",
    ["Starting to Eat"] = "Al empezar a comer", ["Finishing Eating"] = "Al terminar de comer",
    ["Starting to Drink"] = "Al empezar a beber", ["Finishing Drinking"] = "Al terminar de beber",
    ["Entering a Rest Area"] = "Al entrar en una zona de descanso",
    ["Leaving a Rest Area"] = "Al salir de una zona de descanso", ["AFK"] = "Ausente",
    ["Using a Hearthstone"] = "Al usar una piedra de hogar",
    ["Equipping This Outfit"] = "Al equipar este conjunto",
    ["Target Friendly Player"] = "Jugador amistoso como objetivo",
    ["Target Friendly NPC"] = "PNJ amistoso como objetivo",
    ["Target Hostile NPC"] = "PNJ hostil como objetivo",
    ["Drag or click to pick up the macro."] = "Arrastra o haz clic para recoger la macro.",
    ["Right-click for favorite options."] = "Haz clic derecho para ver las opciones de favoritos.",
    ["You have not collected this toy."] = "No has obtenido este juguete.",
    ["Right-click to remove this custom toy."] = "Haz clic derecho para eliminar este juguete personalizado.",
    ["Valid behavior is not guaranteed."] = "No se garantiza que funcione correctamente.",
    ["Summons a random favorite battle pet."] = "Invoca una mascota de duelo favorita al azar.",
    ["Selecting a specific pet turns this off."] = "Seleccionar una mascota específica desactiva esta opción.",
    ["Summons a random mount from this category."] = "Invoca una montura aleatoria de esta categoría.",
    ["Selecting specific mounts turns this off."] = "Seleccionar monturas específicas desactiva esta opción.",
    ["Select a title for this transmog outfit"] = "Selecciona un título para este conjunto de transfiguración",
    ["Save all Fitter settings from the selected outfit."] = "Guarda todos los ajustes de Fitter del conjunto seleccionado.",
    ["Add a toy to Fitter's cosmetic toy list using its item ID."] = "Añade un juguete a la lista de juguetes cosméticos de Fitter mediante su ID de objeto.",
    ["Leave the currently summoned pet unchanged, except when a global dismissal setting applies."] = "Deja sin cambios la mascota invocada, excepto cuando se aplique un ajuste global para retirarla.",
    ["No conditions selected. This emote can occur whenever its trigger fires."] = "No hay condiciones seleccionadas. Este gesto puede ocurrir cuando se active su evento.",
    ["Select all zones."] = "Selecciona todas las zonas.", ["Clear all selected zones."] = "Borra todas las zonas seleccionadas.",
    ["Reset outfits that have only the default Hearthstone selected?\n\nThis applies now to this character and when each other character on the account next logs in."] = "¿Restablecer los conjuntos que solo tienen seleccionada la piedra de hogar predeterminada?\n\nEsto se aplica ahora a este personaje y a los demás personajes de la cuenta la próxima vez que inicien sesión.",
    ["Apply the loadout |cffffd200%s|r to the currently selected outfit?\n\nThis will replace its current Fitter configuration."] = "¿Aplicar la configuración |cffffd200%s|r al conjunto seleccionado?\n\nEsto reemplazará su configuración actual de Fitter.",
    ["Delete the loadout |cffffd200%s|r?\n\nThis cannot be undone."] = "¿Eliminar la configuración |cffffd200%s|r?\n\nEsta acción no se puede deshacer.",
    ["Reset all Fitter outfit configurations for this character?\n\nSaved loadouts and custom emotes will be preserved. This cannot be undone."] = "¿Restablecer todas las configuraciones de conjuntos de Fitter para este personaje?\n\nSe conservarán las configuraciones guardadas y los gestos personalizados. Esta acción no se puede deshacer.",
    ["Reset the Fitter configuration for |cffffd200%s|r?\n\nThis cannot be undone."] = "¿Restablecer la configuración de Fitter para |cffffd200%s|r?\n\nEsta acción no se puede deshacer.",
    ["Cannot create macro: maximum number of account macros reached."] = "No se puede crear la macro: se alcanzó el máximo de macros de cuenta.",
    ["Created macro '%s'."] = "Se creó la macro '%s'.",
    ["Character macro '%s' already exists."] = "La macro de personaje '%s' ya existe.",
    ["Cannot create macro: maximum number of character macros reached."] = "No se puede crear la macro: se alcanzó el máximo de macros de personaje.",
    ["Created character macro '%s'."] = "Se creó la macro de personaje '%s'.",
}

for key, value in pairs(translations) do
    L[key] = value
end
