local _, ns = ...
if GetLocale() ~= "zhCN" then return end
local L = ns.L

local translations = {
    ["Account"] = "账号", ["Account Wide"] = "全账号通用",
    ["Apply"] = "应用", ["Delete"] = "删除",
    ["Account Wide Aquatic Mounts"] = "全账号水生坐骑",
    ["Account Wide Flying Mounts"] = "全账号飞行坐骑",
    ["Account Wide Ground Mounts"] = "全账号陆行坐骑",
    ["Active"] = "激活", ["Add New Emote"] = "添加新表情",
    ["Add New Loadout"] = "添加新配置",
    ["Add Toy By ID"] = "通过 ID 添加玩具", ["Added Toys"] = "已添加的玩具",
    ["Animation"] = "动画", ["Apply Loadout"] = "应用配置",
    ["Aquatic"] = "水生", ["Associated Outfits:"] = "关联套装：",
    ["Available to"] = "适用于", ["Cancel"] = "取消",
    ["Character"] = "角色", ["Character Title"] = "角色头衔",
    ["Check All"] = "全选", ["Clear"] = "清除", ["Conditions:"] = "条件：",
    ["Cosmetic Toys"] = "外观玩具",
    ["Create Character Outfit Update Macro"] = "创建角色套装更新宏",
    ["Create Macro"] = "创建宏",
    ["Create Outfit Update Macro"] = "创建套装更新宏",
    ["Custom"] = "自定义", ["Default"] = "默认",
    ["Delete Emote"] = "删除表情", ["Delete Loadout"] = "删除配置",
    ["Disable Hunter Pets"] = "禁用猎人宠物",
    ["Disable Pets"] = "禁用宠物", ["Disabled"] = "已禁用",
    ["Emote text"] = "表情文本", ["Emotes"] = "表情",
    ["Enter a toy item ID"] = "输入玩具物品 ID",
    ["Flying"] = "飞行", ["General"] = "常规",
    ["Global Cooldown"] = "公共冷却时间", ["Ground"] = "陆行",
    ["Hearthstone Macro"] = "炉石宏", ["Hearthstones"] = "炉石",
    ["Hide Duplicate Names"] = "隐藏重复名称", ["Hunter Pet"] = "猎人宠物",
    ["Hunter Pets"] = "猎人宠物", ["Icon"] = "图标",
    ["Ignore Hunter Pet"] = "忽略猎人宠物", ["Ignore Pet"] = "忽略宠物",
    ["Ignore Pets"] = "忽略宠物", ["Ignore target"] = "忽略目标",
    ["Ignore Title"] = "忽略头衔", ["In Stable"] = "兽栏中",
    ["Loadouts"] = "预设配置", ["Mount Macro"] = "坐骑宏",
    ["Name"] = "名称", ["None"] = "无", ["Not Collected"] = "未收集",
    ["Outfits"] = "套装", ["Pets"] = "宠物", ["Preview"] = "预览",
    ["Random Mount"] = "随机坐骑", ["Random Pet"] = "随机宠物",
    ["Random Hunter Pet"] = "随机猎人宠物",
    ["Remove Added Toy"] = "移除已添加玩具", ["Remove Favorite"] = "取消偏好",
    ["Reset"] = "重置", ["Reset Default Hearthstones"] = "重置默认炉石",
    ["Save"] = "保存", ["Save for"] = "保存至", ["Save Loadout"] = "保存配置",
    ["Search"] = "搜索", ["Search by ID"] = "按 ID 搜索", ["Select All"] = "全选",
    ["Selected"] = "已选择", ["Set Favorite"] = "设为偏好",
    ["Stabled"] = "兽栏中", ["Summon Mount"] = "召唤坐骑",
    ["Summon Pet"] = "召唤宠物", ["This Character"] = "当前角色",
    ["Title"] = "头衔", ["Title (optional)"] = "头衔（可选）",
    ["Uncheck All"] = "取消全选", ["Unnamed"] = "未命名",
    ["Unnamed Loadout"] = "未命名配置", ["Update Outfit"] = "更新套装",
    ["Character Loadout"] = "角色配置",
    ["Account Wide Loadout"] = "全账号配置",
    ["No Pet"] = "无宠物", ["Random"] = "随机", ["Toys"] = "玩具",
    ["Use Hearthstone"] = "使用炉石", ["Voiceline"] = "语音短句",
    ["Zones"] = "区域", ["Page %d/%d"] = "页码 %d/%d", ["Ignore %s"] = "忽略 %s",
    ["Mounts"] = "坐骑", ["Remove Macro Changes On Update"] = "更新时移除宏修改",
    ["Show Tooltip in Mount Macro"] = "在坐骑宏中显示鼠标提示",
    ["Use Druid Macro"] = "使用德鲁伊宏", ["Use Shaman Macro"] = "使用萨满祭司宏",
    ["Use Zone Specific Mounts"] = "使用特定区域坐骑",
    ["Show Tooltip in Hearthstone Macro"] = "在炉石宏中显示鼠标提示",
    ["Astral Recall Fallback"] = "备用星界传送",
    ["Dismiss Pet On Stealth"] = "进入潜行时解散宠物",
    ["Dismiss Pet In Instances While Grouped"] = "组队进入副本时解散宠物",
    ["Revive Pet"] = "复活宠物",
    ["Cancel Non-Outfit Cosmetic Toys"] = "取消非套装外观玩具",
    ["Apply Toy On Select"] = "选中时应用玩具",
    ["Auto Enable Zone Situations"] = "自动启用区域情境",
    ["Auto Disable Zone Situations"] = "自动禁用区域情境",
    ["Disable %s"] = "禁用 %s", ["%s Condition"] = "%s 条件",
    ["%s Condition:"] = "%s 条件：", ["Classic"] = "经典旧世",
    ["Burning Crusade"] = "燃烧的远征", ["Wrath of the Lich King"] = "巫妖王之怒",
    ["Cataclysm"] = "大地的裂变", ["Mists of Pandaria"] = "熊猫人之谜",
    ["Warlords of Draenor"] = "德拉诺之王", ["Legion"] = "军团再临",
    ["Battle for Azeroth"] = "争霸艾泽拉斯", ["Shadowlands"] = "暗影国度",
    ["Dragonflight"] = "巨龙时代", ["The War Within"] = "地心之战",
    ["Midnight"] = "至暗之夜", ["Humanoid"] = "人型生物", ["Dragonkin"] = "龙类",
    ["Undead"] = "亡灵", ["Critter"] = "小动物", ["Magic"] = "魔法",
    ["Elemental"] = "元素", ["Beast"] = "野兽", ["Mechanical"] = "机械",
    ["Arctic"] = "极地", ["Forest"] = "森林", ["Jungle"] = "丛林",
    ["Desert"] = "沙漠", ["Plains"] = "平原", ["Mountain"] = "山脉",
    ["Swamp"] = "沼泽", ["Cities"] = "城市", ["Biomes"] = "生态群落",
    ["Khaz Algar"] = "卡兹阿加", ["K'aresh"] = "卡雷什", ["Dragon Isles"] = "巨龙群岛",
    ["Kul Tiras"] = "库尔提拉斯", ["Zandalar"] = "赞达拉", ["Nazjatar"] = "纳斯雅塔尔",
    ["Broken Isles"] = "破碎群岛", ["Argus"] = "阿古斯", ["Draenor"] = "德拉诺",
    ["Pandaria"] = "潘达利亚", ["Northrend"] = "诺森德", ["Outland"] = "外域",
    ["Eastern Kingdoms"] = "东部王国", ["Kalimdor"] = "卡利姆多",
    ["Elemental Planes"] = "元素位面",
    ["Social"] = "社交", ["Outfit Change"] = "更换套装",
    ["Enter World"] = "进入世界", ["Mount"] = "骑乘", ["Dismount"] = "下座骑",
    ["Zone Change"] = "切换区域", ["Leave Stealth"] = "脱离潜行",
    ["Mounting"] = "正在上座骑", ["Dismounting"] = "正在下座骑",
    ["Entering Combat"] = "进入战斗", ["Leaving Combat"] = "脱离战斗",
    ["Starting to Eat"] = "开始进食", ["Finishing Eating"] = "结束进食",
    ["Starting to Drink"] = "开始饮水", ["Finishing Drinking"] = "结束饮水",
    ["Entering a Rest Area"] = "进入休息区",
    ["Leaving a Rest Area"] = "离开休息区", ["AFK"] = "暂离",
    ["Using a Hearthstone"] = "使用炉石",
    ["Equipping This Outfit"] = "装备此套装",
    ["Target Friendly Player"] = "选中友好玩家",
    ["Target Friendly NPC"] = "选中友好 NPC",
    ["Target Hostile NPC"] = "选中敌对 NPC",
    ["Drag or click to pick up the macro."] = "拖动或点击以拾取宏。",
    ["Right-click for favorite options."] = "右键点击查看偏好选项。",
    ["You have not collected this toy."] = "你尚未收集此玩具。",
    ["Right-click to remove this custom toy."] = "右键点击移除此自定义玩具。",
    ["Valid behavior is not guaranteed."] = "不保证功能完全符合预期。",
    ["Summons a random favorite battle pet."] = "召唤一只随机的偏好战宠。",
    ["Selecting a specific pet turns this off."] = "选择特定宠物将关闭此功能。",
    ["Summons a random mount from this category."] = "召唤该分类下的随机坐骑。",
    ["Selecting specific mounts turns this off."] = "选择特定坐骑将关闭此功能。",
    ["Select a title for this transmog outfit"] = "为此幻化套装选择一个头衔",
    ["Save all Fitter settings from the selected outfit."] = "保存所选套装的所有 Fitter 设置。",
    ["Add a toy to Fitter's cosmetic toy list using its item ID."] = "通过物品 ID 将玩具添加到 Fitter 的外观玩具列表。",
    ["Leave the currently summoned pet unchanged, except when a global dismissal setting applies."] = "保持当前召唤的宠物不变，除非触发了全局解散设置。",
    ["No conditions selected. This emote can occur whenever its trigger fires."] = "未选择任何条件。只要触发条件满足，该表情就会执行。",
    ["Select all zones."] = "选择所有区域。", ["Clear all selected zones."] = "清除所有已选区域。",
    ["Reset outfits that have only the default Hearthstone selected?\n\nThis applies now to this character and when each other character on the account next logs in."] = "重置仅选择了默认炉石的套装？\n\n这将立即应用于当前角色，并在账号下其他角色下次登录时生效。",
    ["Apply the loadout |cffffd200%s|r to the currently selected outfit?\n\nThis will replace its current Fitter configuration."] = "将预设配置 |cffffd200%s|r 应用于当前选择的套装？\n\n这会覆盖其当前的 Fitter 配置。",
    ["Delete the loadout |cffffd200%s|r?\n\nThis cannot be undone."] = "确定删除配置 |cffffd200%s|r 吗？\n\n此操作无法撤销。",
    ["Reset all Fitter outfit configurations for this character?\n\nSaved loadouts and custom emotes will be preserved. This cannot be undone."] = "重置当前角色的所有 Fitter 套装配置？\n\n已保存的配置和自定义表情将被保留。此操作无法撤销。",
    ["Reset the Fitter configuration for |cffffd200%s|r?\n\nThis cannot be undone."] = "重置 |cffffd200%s|r 的 Fitter 配置？\n\n此操作无法撤销。",
    ["Cannot create macro: maximum number of account macros reached."] = "无法创建宏：已达到账号宏数量上限。",
    ["Created macro '%s'."] = "已创建宏 '%s'。",
    ["Character macro '%s' already exists."] = "角色宏 '%s' 已存在。",
    ["Cannot create macro: maximum number of character macros reached."] = "无法创建宏：已达到角色宏数量上限。",
    ["Created character macro '%s'."] = "已创建角色宏 '%s'。",
}

for key, value in pairs(translations) do
    L[key] = value
end
